server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: dingding
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  security:
    user:
      name: admin
      password: admin
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**

logging:
  level:
    root: INFO
    top.roothk.dingding: DEBUG
  file:
    name: logs/dingding.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always